In [2]:
import requests
from lxml import html
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np
import random as rd
import time

In [3]:
headers = {
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78',
    'accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
}
response = requests.get('https://statsroyale.com/cards', headers = headers)
soup = bs(response.text, "html.parser")

CardIndex = {}
data = soup.select('.cards__group')

In [4]:
#獲取卡片名稱，順便取得圖像
Party_Cards = ['Terry', 'Super Lava Hound', 'Super Witch', 'Santa Hog Rider', 'Super Magic Archer', 'Super Mini P.E.K.K.A', 'Super Ice Golem', 'Super Archers', 'Party Hut', 'Party Rocket', 'Warmth']

for i in data:
    Card_type = i.find('div',attrs={"class" : "ui__headerSmall"}).text
    CardIndex[Card_type] = []
    for j in i.find_all('div', attrs ={'class' : 'cards__card'}):
        name = j.find('div', attrs ={'class' : 'ui__tooltip'}).text.strip()
        Elixir = j['data-elixir']
        if name[0] == ' ' :name = name[1:]
        if name[-1] == ' ' :name = name[:-1]
        if name in Party_Cards:continue

        CardIndex[Card_type].append([name, Elixir])

        image_url = j.find('img')['src']
        image_data = requests.get(image_url).content
        with open('../data/Cards/Cards Image/' + name + '.png', 'wb') as image:
            image.write(image_data)
        time.sleep(rd.randint(5, 8))

In [5]:
#抓取14等的資料
#部分網站不完整 需要另外處理
Cards = []
need_skip = ['Rage', 'Heal Spirit', 'Mirror']
index = 0
for i in CardIndex.keys():
    for j in CardIndex[i]:
        if j[0] in need_skip:continue
        link = j[0].replace(' ', '+')
        response = requests.get('https://statsroyale.com/card/' + link, headers = headers)
        page = bs(response.text, "html.parser")
        Rarity = page.find('div', attrs = {'class' : 'card__count'}).text
        if '\n' in Rarity:Rarity = Rarity[:-1]
        Cards.append([i, j[0], Rarity, j[1]])
        time.sleep(rd.randint(5, 8))

        print(Cards[-1])
        
Cards.append(['Spell', 'Rage', 'Epic', '2'])
Cards.append(['Spell', 'Mirror', 'Epic', '1'])
Cards.append(['Troop', 'Heal Spirit', 'Common', '1'])

columns = ['Type', 'Name', 'Rarity', 'Elixir']
df = pd.DataFrame(Cards, columns = columns)[['Type', 'Rarity', 'Name', 'Elixir']]
df

['Troop', 'Knight', 'Common', '3']
['Troop', 'Archers', 'Common', '3']
['Troop', 'Goblins', 'Common', '2']
['Troop', 'Giant', 'Rare', '5']
['Troop', 'P.E.K.K.A', 'Epic', '7']
['Troop', 'Minions', 'Common', '3']
['Troop', 'Balloon', 'Epic', '5']
['Troop', 'Witch', 'Epic', '5']
['Troop', 'Barbarians', 'Common', '5']
['Troop', 'Golem', 'Epic', '8']
['Troop', 'Skeletons', 'Common', '1']
['Troop', 'Valkyrie', 'Rare', '4']
['Troop', 'Skeleton Army', 'Epic', '3']
['Troop', 'Bomber', 'Common', '2']
['Troop', 'Musketeer', 'Rare', '4']
['Troop', 'Baby Dragon', 'Epic', '4']
['Troop', 'Prince', 'Epic', '5']
['Troop', 'Wizard', 'Rare', '5']
['Troop', 'Mini P.E.K.K.A', 'Rare', '4']
['Troop', 'Spear Goblins', 'Common', '2']
['Troop', 'Giant Skeleton', 'Epic', '6']
['Troop', 'Hog Rider', 'Rare', '4']
['Troop', 'Minion Horde', 'Common', '5']
['Troop', 'Ice Wizard', 'Legendary', '3']
['Troop', 'Royal Giant', 'Common', '6']
['Troop', 'Guards', 'Epic', '3']
['Troop', 'Princess', 'Legendary', '3']
['Troop', 'Dark Prince', 'Epic', '4']
['Troop', 'Three Musketeers', 'Rare', '9']
['Troop', 'Lava Hound', 'Legendary', '7']
['Troop', 'Ice Spirit', 'Common', '1']
['Troop', 'Fire Spirit', 'Common', '1']
['Troop', 'Miner', 'Legendary', '3']
['Troop', 'Sparky', 'Legendary', '6']
['Troop', 'Bowler', 'Epic', '5']
['Troop', 'Lumberjack', 'Legendary', '4']
['Troop', 'Battle Ram', 'Rare', '4']
['Troop', 'Inferno Dragon', 'Legendary', '4']
['Troop', 'Ice Golem', 'Rare', '2']
['Troop', 'Mega Minion', 'Rare', '3']
['Troop', 'Dart Goblin', 'Rare', '3']
['Troop', 'Goblin Gang', 'Common', '3']
['Troop', 'Electro Wizard', 'Legendary', '4']
['Troop', 'Elite Barbarians', 'Common', '6']
['Troop', 'Hunter', 'Epic', '4']
['Troop', 'Executioner', 'Epic', '5']
['Troop', 'Bandit', 'Legendary', '3']
['Troop', 'Royal Recruits', 'Common', '7']
['Troop', 'Night Witch', 'Legendary', '4']
['Troop', 'Bats', 'Common', '2']
['Troop', 'Royal Ghost', 'Legendary', '3']
['Troop', 'Ram Rider', 'Legendary', '5']
['Troop', 'Zappies', 'Rare', '4']
['Troop', 'Rascals', 'Common', '5']
['Troop', 'Cannon Cart', 'Epic', '5']
['Troop', 'Mega Knight', 'Legendary', '7']
['Troop', 'Skeleton Barrel', 'Common', '3']
['Troop', 'Flying Machine', 'Rare', '4']
['Troop', 'Wall Breakers', 'Epic', '2']
['Troop', 'Royal Hogs', 'Rare', '5']
['Troop', 'Goblin Giant', 'Epic', '6']
['Troop', 'Fisherman', 'Legendary', '3']
['Troop', 'Magic Archer', 'Legendary', '4']
['Troop', 'Electro Dragon', 'Epic', '5']
['Troop', 'Firecracker', 'Common', '3']
['Troop', 'Mighty Miner', 'Champion', '4']
['Troop', 'Elixir Golem', 'Rare', '3']
['Troop', 'Battle Healer', 'Rare', '4']
['Troop', 'Skeleton King', 'Champion', '4']
['Troop', 'Archer Queen', 'Champion', '5']
['Troop', 'Golden Knight', 'Champion', '4']
['Troop', 'Monk', 'Champion', '5']
['Troop', 'Skeleton Dragons', 'Common', '4']
['Troop', 'Mother Witch', 'Legendary', '4']
['Troop', 'Electro Spirit', 'Common', '1']
['Troop', 'Electro Giant', 'Epic', '7']
['Troop', 'Phoenix', 'Legendary', '4']
['Troop', 'Little Prince', 'Champion', '3']
['Building', 'Cannon', 'Common', '3']
['Building', 'Goblin Hut', 'Rare', '5']
['Building', 'Mortar', 'Common', '4']
['Building', 'Inferno Tower', 'Rare', '5']
['Building', 'Bomb Tower', 'Rare', '4']
['Building', 'Barbarian Hut', 'Rare', '6']
['Building', 'Tesla', 'Common', '4']
['Building', 'Elixir Collector', 'Rare', '6']
['Building', 'X-Bow', 'Epic', '6']
['Building', 'Tombstone', 'Rare', '3']
['Building', 'Furnace', 'Rare', '4']
['Building', 'Goblin Cage', 'Rare', '4']
['Building', 'Goblin Drill', 'Epic', '4']
['Spell', 'Fireball', 'Rare', '4']
['Spell', 'Arrows', 'Common', '3']
['Spell', 'Rocket', 'Rare', '6']
['Spell', 'Goblin Barrel', 'Epic', '3']
['Spell', 'Freeze', 'Epic', '4']
['Spell', 'Lightning', 'Epic', '6']
['Spell', 'Zap', 'Common', '2']
['Spell', 'Poison', 'Epic', '4']
['Spell', 'Graveyard', 'Legendary', '5']
['Spell', 'The Log', 'Legendary', '2']
['Spell', 'Tornado', 'Epic', '3']
['Spell', 'Clone', 'Epic', '3']
['Spell', 'Earthquake', 'Rare', '3']
['Spell', 'Barbarian Barrel', 'Epic', '2']
['Spell', 'Giant Snowball', 'Common', '2']
['Spell', 'Royal Delivery', 'Common', '3']

      Type  Rarity            Name Elixir
0    Troop  Common          Knight      3
1    Troop  Common         Archers      3
2    Troop  Common         Goblins      2
3    Troop    Rare           Giant      5
4    Troop    Epic       P.E.K.K.A      7
..     ...     ...             ...    ...
105  Spell  Common  Giant Snowball      2
106  Spell  Common  Royal Delivery      3
107  Spell    Epic            Rage      2
108  Spell    Epic          Mirror      1
109  Troop  Common     Heal Spirit      1

[110 rows x 4 columns]

In [6]:
#下載進化卡圖片
from lxml import html

page = requests.get('https://www.deckshop.pro/card/list')
tree = html.fromstring(page.content)

pages = tree.xpath('//h3[text()="With evolutions"]/../div/a/img')
for content in pages:
    Evol_Name = 'Evol ' + content.attrib['alt']
    image_url = 'https://www.deckshop.pro' + content.attrib['src']

    image_data = requests.get(image_url).content
    with open('../data/Cards/Cards Image/' + Evol_Name + '.png', 'wb') as image:
        image.write(image_data)

    origin = df.loc[df['Name'] == content.attrib['alt']].values[0]
    df1 = pd.DataFrame([[origin[0], Evol_Name, 'Evolution', origin[3]]], columns = columns)
    df = pd.concat([df, df1])
    print(df.iloc[-1])

    time.sleep(rd.randint(5, 8))

Type               Troop
Rarity         Evolution
Name      Evol Skeletons
Elixir                 1
Name: 0, dtype: object
Type                Troop
Rarity          Evolution
Name      Evol Ice Spirit
Elixir                  1
Name: 0, dtype: object
Type            Troop
Rarity      Evolution
Name      Evol Bomber
Elixir              2
Name: 0, dtype: object
Type          Troop
Rarity    Evolution
Name      Evol Bats
Elixir            2
Name: 0, dtype: object
Type             Troop
Rarity       Evolution
Name      Evol Archers
Elixir               3
Name: 0, dtype: object
Type            Troop
Rarity      Evolution
Name      Evol Knight
Elixir              3
Name: 0, dtype: object
Type                 Troop
Rarity           Evolution
Name      Evol Firecracker
Elixir                   3
Name: 0, dtype: object
Type         Building
Rarity      Evolution
Name      Evol Mortar
Elixir              4
Name: 0, dtype: object
Type        Building
Rarity     Evolution
Name      Evol Tesla
Elixir             4
Name: 0, dtype: object
Type                Troop
Rarity          Evolution
Name      Evol Barbarians
Elixir                  5
Name: 0, dtype: object
Type                 Troop
Rarity           Evolution
Name      Evol Royal Giant
Elixir                   6
Name: 0, dtype: object
Type                    Troop
Rarity              Evolution
Name      Evol Royal Recruits
Elixir                      7
Name: 0, dtype: object
Type              Troop
Rarity        Evolution
Name      Evol Valkyrie
Elixir                4
Name: 0, dtype: object
Type                   Troop
Rarity             Evolution
Name      Evol Wall Breakers
Elixir                     2
Name: 0, dtype: object

In [7]:
df

     Type     Rarity                 Name Elixir
0   Troop     Common               Knight      3
1   Troop     Common              Archers      3
2   Troop     Common              Goblins      2
3   Troop       Rare                Giant      5
4   Troop       Epic            P.E.K.K.A      7
..    ...        ...                  ...    ...
0   Troop  Evolution      Evol Barbarians      5
0   Troop  Evolution     Evol Royal Giant      6
0   Troop  Evolution  Evol Royal Recruits      7
0   Troop  Evolution        Evol Valkyrie      4
0   Troop  Evolution   Evol Wall Breakers      2

[124 rows x 4 columns]

In [8]:
from pandas.api.types import CategoricalDtype

type_order = CategoricalDtype(['Troop', 'Building', 'Spell'], ordered=True)
Rarity_order = CategoricalDtype(['Evolution', 'Champion', 'Legendary', 'Epic', 'Rare', 'Common'], ordered=True)
df['Type'] = df['Type'].astype(type_order)
df['Rarity'] = df['Rarity'].astype(Rarity_order)

df = df.sort_values(by = ['Rarity', 'Type', 'Elixir', 'Name'], ascending=[True, True, False, True]).drop_duplicates()
df

         Type     Rarity                 Name Elixir
0       Troop  Evolution  Evol Royal Recruits      7
0       Troop  Evolution     Evol Royal Giant      6
0       Troop  Evolution      Evol Barbarians      5
0       Troop  Evolution        Evol Valkyrie      4
0       Troop  Evolution         Evol Archers      3
..        ...        ...                  ...    ...
78   Building     Common               Cannon      3
92      Spell     Common               Arrows      3
106     Spell     Common       Royal Delivery      3
105     Spell     Common       Giant Snowball      2
97      Spell     Common                  Zap      2

[124 rows x 4 columns]

In [9]:
df.to_csv('../data/Cards/cards.csv', index = False)